name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
permissions:
  contents: read        # Allows reading the repo contents
  pages: write          # Allows deploying to GitHub Pages
  id-token: write       # Allows requesting an OIDC token
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Add .nojekyll
        run: touch out/.nojekyll

      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
          path: ./out
